import React from 'react';
import Card from '@/components/Card';

const page = () => {
  return (
    <div className="grid grid-cols-5 grid-rows-2 gap-10">
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
      <Card
        id={1}
        cardType="events"
        thumbnailUrl="null"
        title="test"
        artist="test"
        location="test"
        startTime="test"
        endTime="test"
        address="test"
        likeCount={1}
        commentCount={1}
        viewCount={1}
      />
    </div>
  );
};

export default page;
