const date = new Date();
export const MOCKDATA = {
  appPage: [
    {
      id: 1,
      thumbnailUrl: 'https://www.fitpetmall.com/wp-content/uploads/2023/10/230420-0668-1.png',
      title: '방탄소년단 생일 카페1',
      artist: '방탄소년단',
      place: '용산 슈퍼스타 떡볶이',
      startDate: date,
      endDate: date,
      location: '서울시 용산구',
      like: 1,
      comment: 1,
      view: 1,
      joinCount: 1,
    },
    {
      id: 2,
      thumbnailUrl: 'https://blog.kakaocdn.net/dn/tEMUl/btrDc6957nj/NwJoDw0EOapJNDSNRNZK8K/img.jpg',
      title: '방탄소년단 생일 카페2',
      artist: '방탄소년단',
      place: '용산 슈퍼스타 떡볶이',
      startDate: date,
      endDate: date,
      location: '서울시 용산구',
      like: 2,
      comment: 2,
      view: 2,
      joinCount: 2,
    },
    {
      id: 3,
      thumbnailUrl: 'https://ichef.bbci.co.uk/news/640/cpsprodpb/E172/production/_126241775_getty_cats.png',
      title: '방탄소년단 생일 카페3',
      artist: '방탄소년단',
      place: '용산 슈퍼스타 떡볶이',
      startDate: date,
      endDate: date,
      location: '서울시 용산구',
      like: 3,
      comment: 3,
      view: 3,
      joinCount: 3,
    },
    {
      id: 4,
      thumbnailUrl:
        'https://t1.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/4arX/image/rZ1xSXKCJ4cd-IExOYahRWdrqoo.jpg',
      title: '방탄소년단 생일 카페4',
      artist: '방탄소년단',
      place: '용산 슈퍼스타 떡볶이',
      startDate: date,
      endDate: date,
      location: '서울시 용산구',
      like: 4,
      comment: 4,
      view: 4,
      joinCount: 4,
    },
    {
      id: 5,
      thumbnailUrl:
        'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/kVe/image/i16oISROMcKXVyuQUWEY26qjF5E.jpg',
      title: '방탄소년단 생일 카페5',
      artist: '방탄소년단',
      place: '용산 슈퍼스타 떡볶이',
      startDate: date,
      endDate: date,
      location: '서울시 용산구',
      like: 5,
      comment: 5,
      view: 5,
      joinCount: 5,
    },
  ],
};
