import { Metadata } from 'next';
import RecoilRootWrapper from '../utils/RecoilRootWrapper';
import ReactQueryWrapper from '@/utils/ReactQueryWrapper';
import { ThemeProvider } from '../containers/mypage/Hd-material-tailwind';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/global.css';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer/Footer';
import { AuthProvider } from '@/context/AuthContext';

export const metadata: Metadata = {
  title: 'Happi Day',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/gh/sun-typeface/SUIT/fonts/static/woff2/SUIT.css" rel="stylesheet" />
      </head>
      <body>
        <RecoilRootWrapper>
          <ReactQueryWrapper>
            <AuthProvider>
              <Nav />
              {children}
              <Footer />
            </AuthProvider>
            <ToastContainer />
          </ReactQueryWrapper>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
